GitUserSearch/Models/ErrorViewModel.cs
using System;

namespace GitUserSearch.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GitUserSearch/Models/GitUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace GitUserSearch.Models
{
    public class GitUser
    {
        // Required attributes
        [Key, Display(Name = "Git ID")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
        
        public string Login { get; set; }
        [Display(Name = "User Url")]
        public string Url { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public int Followers { get; set; }

        // Nonable attributes
        public string Company { get; set; }
        public string Email { get; set; }
    }
}

GitUserSearch/Models/UserSearch.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GitUserSearch.Models
{
    public class UserSearch
    {
        [Display(Name = "Search ID")]
        public int Id { get; set; }

        [Required, Display(Name = "Access Date")]
        public DateTime AccessDate { get; set; }

        [Display(Name = "User Login")]
        public GitUser User { get; set; }
    }
}

GitUserSearch/Controllers/HistoryController.cs
using System.Threading.Tasks;
using GitUserSearch.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GitUserSearch.Controllers
{
    public class HistoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        // Initialize controller by injecting DbContext
        public HistoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: History
        // Display all user search history in a brief way
        public async Task<IActionResult> Index()
        {
            var searchHistory = _context.UserSearches.Include(s => s.User);

            return View(await searchHistory.ToListAsync());
        }

        // GET: History/Details/5
        // Display all details of a valid user via its user id
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.GitUsers.SingleOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
    }
}

GitUserSearch/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GitUserSearch.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net;
using Octokit;

namespace GitUserSearch.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        //public async Task<IActionResult> ShowAllUsers()
        //{
        //    List<Octokit.User> users = new List<Octokit.User>();
            
        //    try
        //    {
        //        string url = "https://api.github.com/users";
        //        var client = new HttpClient();
        //        client.BaseAddress = new Uri("https://api.github.com/users");
        //        //var client = new GitHubClient(new ProductHeaderValue("MyDemoApp"));
                
        //            var response = await client.GetAsync($"/users");
        //            response.EnsureSuccessStatusCode();

        //            var stringResult = await response.Content.ReadAsStringAsync();
        //            var rawWeather = JsonConvert.DeserializeObject<List<Octokit.User>>(stringResult);
        //            return View(users);
        //        }
        //        catch (HttpRequestException httpRequestException)
        //        {
        //            return BadRequest($"Error getting weather from OpenWeather: {httpRequestException.Message}");
        //        }

        //        //var rawJSON = string.Empty;
        //        //rawJSON = webClient.DownloadString(url);
                
        //        //users = JsonConvert.DeserializeObject<List<Octokit.User>>(rawJSON);

        //        //return View(users);
        //    }


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GitUserSearch/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GitUserSearch.Data;
using GitUserSearch.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Octokit;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GitUserSearch.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: User/
        public IActionResult Index()
        {
            return View();
        }

        // GET: User/Search?username=<username>
        public async Task<IActionResult> Search(string username)
        {
            try
            {
                var github = new GitHubClient(new ProductHeaderValue("MyDemoApp"));
                var user = await github.User.Get(username);

                await AddToDB(user);

                return View(user);
            }
            catch (NotFoundException objectNotFound)
            {
                TempData["Message"] = "No Valid User Found! Please Search Again!";

                return Redirect("index");
            // BadRequest($"Error getting user info from github : {ObjectNotFoundException.Message}");
            }
        }

        // An utility method to add new user to dbcontext and database
        // Only run when a search found a valid user
        private async Task AddToDB(User user)
        {
            try
            {
                // Check if newly searched user already exists in the DbContext
                var gitUser = _context.GitUsers.SingleOrDefault(u => u.Id == user.Id);

                // Create a new GitUser if not existing in the DbContext
                if (gitUser == null) {
                    gitUser = new GitUser
                    {
                        Login = user.Login,
                        Id = user.Id,
                        Url = user.Url,
                        Name = user.Name,
                        Location = user.Location,
                        Followers = user.Followers,
                        Company = user.Company,
                        Email = user.Email
                    };
                    _context.GitUsers.Add(gitUser);
                }

                // Create new search item using the searched user
                UserSearch search = new UserSearch { AccessDate = DateTime.Now, User = gitUser };
                _context.UserSearches.Add(search);

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException e)
            {
                Console.WriteLine(e.Message);
                throw;
            }
        }
    }
}

GitUserSearch/Views/History/Details.cshtml
@model GitUser

@{
    ViewData["Title"] = "User Details";
}

<h2>@ViewData["Title"]</h2>
<hr />

<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">User ID: @Html.DisplayFor(Model => Model.Id)</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
                <div class=" col-md-9 col-lg-9 ">
                    <table class="table table-user-information">
                        <tbody>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Id):</td>
                                <td>@Html.DisplayFor(Model => Model.Id)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Login):</td>
                                <td>@Html.DisplayFor(Model => Model.Login)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Name)</td>
                                <td>@Html.DisplayFor(Model => Model.Name)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Location)</td>
                                <td> @Html.DisplayFor(Model => Model.Location)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Followers)</td>
                                <td>@Html.DisplayFor(Model => Model.Followers)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Url)</td>
                                <td>@Html.DisplayFor(Model => Model.Url)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Email)</td>
                                <td>@Html.DisplayFor(Model => Model.Email)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Company)</td>
                                <td>@Html.DisplayFor(Model => Model.Company)</td>
                            </tr>
                        </tbody>
                    </table>
                    <hr />
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <a asp-controller="History" class="btn btn-primary" asp-action="Index">Back</a>
            <span class="pull-right">
                <a asp-controller="User" class="btn btn-primary" asp-action="Index">Search Again</a>
            </span>
        </div>
    </div>
</div>

GitUserSearch/Views/History/Index.cshtml
@model IEnumerable<UserSearch>

@{
    ViewData["Title"] = "Search History";
}

<h2>@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-striped table-hover">
            <thead >
                <tr class="success">
                    <th>
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AccessDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.User)
                    </th>
                    <th>
                        Operation
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AccessDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.Login)
                        </td>
                        <td>
                            <a asp-action="Details" asp-route-id="@item.User.Id" class="btn-sm btn-success">Details</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
<div>
    <a asp-controller="User" class="btn btn-primary" asp-action="Index">Back to Search</a>
</div>

GitUserSearch/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

GitUserSearch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GitUserSearch</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">GitUserSearch</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="User" asp-action="Index">Search</a></li>
                    <li><a asp-area="" asp-controller="History" asp-action="Index">History</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="clear:both">
            <p>&copy; 2018 - Charles Cheng - GitUserSearch</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

GitUserSearch/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Search User";
}

<script type="text/javascript">
    Document.ready(function () {
        $("#NotificationDiv").show();
    });
</script>

@if (TempData["Message"] != null)
{
<div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong><span class="glyphicon glyphicon-remove"></span> Failed: </strong>
    @TempData["Message"]
</div>
}

<h2>@ViewData["Title"]</h2>
<hr />

<h4>Please input github username</h4>
<form class="form-inline" asp-controller="User" asp-action="Search" method="get">
    <div class="form-group">
        <label for="exampleInputName2">User Name</label>
        <input type="text" class="form-control" placeholder="User Name" name="username" required
               oninvalid="this.setCustomValidity('Please Enter GitHub User Name Here')"
               oninput="this.setCustomValidity('')">
        <input type="submit" class="btn btn-primary" value="Search" />
    </div>
</form>

GitUserSearch/Views/User/Search.cshtml
@model Octokit.User

@{
    ViewData["Title"] = "User Profile";
}

<div id="NotificationDiv">
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            X
        </button>
        Search Successful! Valid user found!
    </div>
</div>

<h2>@ViewData["Title"]</h2>
<hr />

<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">User ID: @Html.DisplayFor(Model => Model.Id)</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
                <div class=" col-md-9 col-lg-9 ">
                    <table class="table table-user-information">
                        <tbody>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Id):</td>
                                <td>@Html.DisplayFor(Model => Model.Id)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Login):</td>
                                <td>@Html.DisplayFor(Model => Model.Login)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Name)</td>
                                <td>@Html.DisplayFor(Model => Model.Name)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Location)</td>
                                <td> @Html.DisplayFor(Model => Model.Location)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Followers)</td>
                                <td>@Html.DisplayFor(Model => Model.Followers)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Url)</td>
                                <td>@Html.DisplayFor(Model => Model.Url)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Email)</td>
                                <td>@Html.DisplayFor(Model => Model.Email)</td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayNameFor(Model => Model.Company)</td>
                                <td>@Html.DisplayFor(Model => Model.Company)</td>
                            </tr>
                        </tbody>
                    </table>
                    <hr />
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <a asp-controller="User" class="btn btn-primary" asp-action="Index">Back to Search</a>
            
            <span class="pull-right">
                <a asp-controller="History" class="btn btn-primary" asp-action="Index">Search History</a>
            </span>
        </div>
    </div>
</div>